apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config

data:
  PORT: "3000"
  MONGO_URI: "mongodb://host.minikube.internal:27017/order-management"
  TENANT_API_KEY: "x-tenant-id"
  MAIL: "vasanthdevcode@gmail.com"